# playbooks/examples/Batch_Parallel.yml
---
- name: SOAP Batch Parallel Example
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Send SOAP requests in parallel
      hufschlaeger.soap_client.soap_batch:
        requests:
          - endpoint_url: https://www.dataaccess.com/webservicesserver/NumberConversion.wso
            soap_action: NumberToWords
            body_dict:
              NumberToWords:
                ubiNum: 1
            namespace: http://www.dataaccess.com/webservicesserver/

          - endpoint_url: https://www.dataaccess.com/webservicesserver/NumberConversion.wso
            soap_action: NumberToWords
            body_dict:
              NumberToWords:
                ubiNum: 2
            namespace: http://www.dataaccess.com/webservicesserver/

          - endpoint_url: https://www.dataaccess.com/webservicesserver/NumberConversion.wso
            soap_action: NumberToWords
            body_dict:
              NumberToWords:
                ubiNum: 3
            namespace: http://www.dataaccess.com/webservicesserver/

          - endpoint_url: https://www.dataaccess.com/webservicesserver/NumberConversion.wso
            soap_action: NumberToWords
            body_dict:
              NumberToWords:
                ubiNum: 4
            namespace: http://www.dataaccess.com/webservicesserver/

          - endpoint_url: https://www.dataaccess.com/webservicesserver/NumberConversion.wso
            soap_action: NumberToWords
            body_dict:
              NumberToWords:
                ubiNum: 5
            namespace: http://www.dataaccess.com/webservicesserver/

        parallel: true
        max_workers: 3
        stop_on_error: false
      register: parallel_result

    - name: Show parallel results
      debug:
        msg: "Completed {{ parallel_result.successful }}/{{ parallel_result.total }} in parallel"
