---
- name: Test CountryInfoService
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Get Country Name by ISO Code"
      hufschlaeger.soap_client.soap_request:
        endpoint_url: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"
        soap_action: ""
        body_dict:
          sCountryISOCode: "DE"
        body_root_tag: "CountryName"
        namespace: "http://www.oorsprong.org/websamples.countryinfo"
        namespace_prefix: "web"
        soap_version: "1.1"
        headers:
          Content-Type: "text/xml; charset=utf-8"
        validate_certs: yes
        timeout: 30
      register: result

    - name: Show CountryInfoService Result
      debug:
        msg:
          - "Status: {{ result.status_code }}"
          - "Response: {{ result.body }}"
          - "Success: {{ result.success }}"