---
- name: Test NumberToDollars
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Number to Dollars"
      hufschlaeger.soap_client.soap_request:
        endpoint_url: "https://www.dataaccess.com/webservicesserver/NumberConversion.wso"
        soap_action: ""
        body_dict:
          dNum: "1234.56"
        body_root_tag: "NumberToDollars"
        namespace: "http://www.dataaccess.com/webservicesserver/"
        namespace_prefix: "ns"
        soap_version: "1.1"
        headers:
          Content-Type: "text/xml; charset=utf-8"
        validate_certs: yes
        timeout: 30
      register: result

    - name: Show NumberToDollars Result
      debug:
        msg:
          - "Status: {{ result.status_code }}"
          - "Response: {{ result.body }}"
          - "Success: {{ result.success }}"
