---
- name: Test SOAP Module
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Test NumberToWords Service
      soap_request:
        endpoint_url: "https://www.dataaccess.com/webservicesserver/NumberConversion.wso"
        soap_action: ""
        body_dict:
          ubiNum: 500
        body_root_tag: "NumberToWords"
        namespace: "http://www.dataaccess.com/webservicesserver/"
        namespace_prefix: "ns"
        soap_version: "1.1"
        headers:
          Content-Type: "text/xml; charset=utf-8"
        validate_certs: yes
      register: result

    - name: Show NumberToWords Result
      debug:
        msg:
          - "Status: {{ result.status_code }}"
          - "Response: {{ result.body }}"
          - "Success: {{ result.success }}"
