---
name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core ansible-lint
          pip install -r requirements.txt

      - name: Run ansible-lint
        run: |
          ansible-lint playbooks/examples/**/*.yml || true
        continue-on-error: true

  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core
          pip install -r requirements.txt

      # ✅ FIX: Collection ERST installieren!
      - name: Build collection
        run: |
          ansible-galaxy collection build --force

      - name: Install collection
        run: |
          ansible-galaxy collection install *.tar.gz --force

      - name: Check playbook syntax
        run: |
          # Teste alle Playbooks
          echo "Testing validation playbooks..."
          for playbook in playbooks/examples/validation/*.yml; do
            if [ -f "$playbook" ]; then
              echo "✓ Checking: $playbook"
              ansible-playbook "$playbook" --syntax-check
            fi
          done
          
          echo ""
          echo "Testing request playbooks..."
          for playbook in playbooks/examples/request/*.yml; do
            if [ -f "$playbook" ]; then
              echo "✓ Checking: $playbook"
              ansible-playbook "$playbook" --syntax-check
            fi
          done
          
          echo ""
          echo "Testing batch playbooks..."
          for playbook in playbooks/examples/batch/*.yml; do
            if [ -f "$playbook" ]; then
              echo "✓ Checking: $playbook"
              ansible-playbook "$playbook" --syntax-check
            fi
          done

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest tests/ -v --cov=plugins/module_utils/soap_module

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true

  build-collection:
    name: Build Collection
    runs-on: ubuntu-latest
    needs: [lint, syntax-check, unit-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core

      - name: Build collection
        run: |
          ansible-galaxy collection build --force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: collection
          path: "*.tar.gz"
          retention-days: 7

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build-collection

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core
          pip install -r requirements.txt

      - name: Download collection artifact
        uses: actions/download-artifact@v4
        with:
          name: collection

      - name: Install collection
        run: |
          ansible-galaxy collection install *.tar.gz --force

      - name: Run validation examples
        run: |
          echo "Running validation examples..."
          for playbook in playbooks/examples/validation/*.yml; do
            if [ -f "$playbook" ]; then
              echo "▶ Running: $playbook"
              ansible-playbook "$playbook" -v || echo "⚠ Warning: $playbook failed (external service issue?)"
            fi
          done
        continue-on-error: true

      - name: Run request examples
        run: |
          echo "Running request examples..."
          # Nur stabile Examples
          ansible-playbook playbooks/examples/request/Request_NumberToWords.yml -v
        continue-on-error: true